import express, { Request, Response } from "express";
import PDFDocument from "pdfkit";

const router = express.Router();

router.post("/getPDF", async (request: Request, response: Response) => {
  try {
    // Create a new PDF document
    const doc = new PDFDocument();
    
    // Set response headers for PDF
    response.header('Content-Type', 'application/pdf');
    response.header('Content-Disposition', 'attachment; filename="document.pdf"');
    
    // Pipe the PDF into the response
    doc.pipe(response);
    
    // Add content to the PDF
    doc.fontSize(20).text('Generated PDF Document', 100, 100);
    doc.fontSize(12).text('This PDF was generated by the getPDF API endpoint.', 100, 150);
    doc.text('Date: ' + new Date().toLocaleDateString(), 100, 180);
    
    // You can add more content based on request data
    if (request.body && request.body.content) {
        doc.text('Custom Content:', 100, 220);
        doc.text(request.body.content, 100, 250);
    }
    
    // Finalize the PDF
    doc.end();
    
  } catch (error) {
    console.error('Error serving PDF:', error);
    return response.status(500).json({ error: 'Failed to serve PDF file.' });
  }
});

export default router;